
title: 2019 My LA2050 Grants Challenge
description: >-
  The My LA2050 Grants Challenge is an open call for ideas that
  will activate 100,000 Angelenos to make LA the best place to
  learn, create, play, connect, and live.
image: https://challenge.la2050.org/assets/images/home/2048-wide/collaborates.jpg

mailing_list_url: https://la2050.us6.list-manage.com/subscribe/post?u=81b6d7b4efb839b992bf7ae72&amp;id=b16f498212
# submission_url: https://activationla2050.smapply.io/prog/challenge_info/

# Our form:
vote_url: /vote/form/


# New challenge announced: 
# January 8
phase: 1

# Entries being accepted: 
# February 28
# phase: 2

# Entry period ended: 
# March 29
# phase: 3

# Entries shown on the website: 
# April 15
# phase: 4
# NOTE: If you switch to “phase: 4”, you’ll also want to
# uncomment the “collections” so the entry pages will appear.

# collections:
#   learn:
#     output: true
#     permalink: /learn/:path/
#   create:
#     output: true
#     permalink: /create/:path/
#   play:
#     output: true
#     permalink: /play/:path/
#   connect:
#     output: true
#     permalink: /connect/:path/
#   live:
#     output: true
#     permalink: /live/:path/

# Votes being accepted: 
# April 22
# phase: 5

# Voting period ended: 
# April 29
# phase: 6

# Winners announced: 
# June 4
# phase: 7


winners:
  # 1)
  - /learn/center-for-innovation-in-stem-education-cise/
  # 2)
  - /create/east-la-community-corporation-elacc/
  # 3)
  - /play/the-brady-center-to-prevent-gun-violence/
  # 4)
  - /connect/mirys-list/
  # 5)
  - /live/united-way-of-greater-los-angeles/


auth0_js_url: https://cdn.auth0.com/js/auth0/9.5.1/auth0.min.js
# auth0_domain: activation-la2050.auth0.com
auth0_domain: auth0-activation.la2050.org
auth0_client_id: INfJpr4dnNk2EN143utsZYz4Zeq9c7cd

voting_enable_auth0: true

voting_enable_phone: true
voting_enable_email: true
voting_enable_facebook: true

voting_maintance_mode: false
voting_test_mode: false

voting_strict_mode: true

# For cache busting
version: 1.8.3


permalink: pretty

exclude:
  - CNAME
  - README
  - Gemfile
  - Gemfile.lock
  - _node
  - sitemap.txt
  - assets/images/learn/original
  - assets/images/create/original
  - assets/images/play/original
  - assets/images/connect/original
  - assets/images/live/original
  - assets/images/goals/original
  - assets/images/home/original
  - assets/images/vote/original

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: learn
    values:
      layout: project
      body_class: blueberry
  - scope:
      path: ""
      type: create
    values:
      layout: project
      body_class: banana
  - scope:
      path: ""
      type: play
    values:
      layout: project
      body_class: strawberry
  - scope:
      path: ""
      type: connect
    values:
      layout: project
      body_class: tangerine
  - scope:
      path: ""
      type: live
    values:
      layout: project
      body_class: lime
