
title: 2019 My LA2050 Grants Challenge
description: >-
  The My LA2050 Grants Challenge is an open call for ideas to make LA the best place to
  learn, create, play, connect, and live.
image: https://challenge.la2050.org/assets/images/city-illustration/square.png

mailing_list_url: https://la2050.us6.list-manage.com/subscribe/post?u=81b6d7b4efb839b992bf7ae72&amp;id=b16f498212
submission_url: https://challengela2050.smapply.io

# Our form:
vote_url: /vote/form/

year: 2019

# New challenge announced: 
# January 8
# phase: 1

# Entries being accepted: 
# February 28
phase: 2

# Entry period ended: 
# March 29
# phase: 3

# Entries shown on the website: 
# April 15
# phase: 4
# NOTE: If you switch to “phase: 4”, you’ll also want to
# uncomment the “collections” so the entry pages will appear.

# collections:
#   learn:
#     output: true
#     permalink: /learn/:path/
#   create:
#     output: true
#     permalink: /create/:path/
#   play:
#     output: true
#     permalink: /play/:path/
#   connect:
#     output: true
#     permalink: /connect/:path/
#   live:
#     output: true
#     permalink: /live/:path/

# Votes being accepted: 
# April 22
# phase: 5

# Voting period ended: 
# April 29
# phase: 6

# Finalists announced: 
# ?
# phase: 7

# Winners announced: 
# June 4
# phase: 8


finalists:

  # Learn
  # 1)
  - /learn/big-brothers-big-sisters-of-greater-los-angeles/
  # 2)
  - /learn/charles-r-drew-university-of-medicine-and-science/
  # 3)
  - /learn/center-for-innovation-in-stem-education-cise/
  # 4)
  - /learn/common-sense/
  # 5)
  - /learn/harlem-lacrosse-los-angeles/
  # 6)
  - /learn/crayon-collection/
  # 7)
  - /learn/proyecto-jardin-a-project-of-hunger-action-la/
  # 8)
  - /learn/all-in-urban-summer-academy/
  # 9)
  - /learn/the-people-of-change/
  # 10)
  - /learn/girls-academic-leadership-academy-gala/

  # Create
  # 1)
  - /create/brioxy/
  # 2)
  - /create/east-la-community-corporation-elacc/
  # 3)
  - /create/long-beach-downtown-development-corporation/
  # 4)
  - /create/make-it-in-la/
  # 5)
  - /create/national-association-of-latino-independent-producers-nalip/
  # 6)
  - /create/civic-innovation-lab/
  # 7)
  - /create/grid110-inc/
  # 8)
  - /create/make-it-in-la/
  # 9)
  - /create/think-tank-productions-inc-dba-think-tank-gallery/
  # 10)
  - /create/get-lit-words-ignite/

  # Play
  # 1)
  - /play/the-brady-center-to-prevent-gun-violence/
  # 2)
  - /play/kounkuey-design-initiative/
  # 3)
  - /play/los-angeles-dodgers-foundation/
  # 4)
  - /play/the-trust-for-public-land/
  # 5)
  - /play/south-bay-bicycle-coalition/
  # 6)
  - /play/red-hen-press/
  # 7)
  - /play/everwild/
  # 8)
  # 9)
  # 10)

  # Connect
  # 1)
  - /connect/casa-of-los-angeles/
  # 2)
  - /connect/film-independent/
  # 3)
  - /connect/city-year-los-angeles/
  # 4)
  - /connect/mirys-list/
  # 5)
  - /connect/voterunlead/
  # 6)
  - /connect/twigg-how-to/
  # 7)
  - /connect/boys-girls-clubs-of-venice-bgcv/
  # 8)
  - /connect/eayikes/
  # 9)
  - /connect/la-forward/
  # 10)
  - /connect/gracias-music-foundation/

  # Live
  # 1)
  - /live/environment-california-research-policy-center/
  # 2)
  - /live/l-a-kitchen/
  # 3)
  - /live/move-la-a-project-of-community-partners/
  # 4)
  - /live/undergraduate-gerontology-and-alzheimers-disease-awareness-association-dba-the-youth-movement-against-alzheimers/
  # 5)
  - /live/united-way-of-greater-los-angeles/
  # 6)
  - /live/süprseed/
  # 7)
  - /live/my-friends-house-inc/
  # 8)
  - /live/lift-los-angeles/
  # 9)
  - /live/mar-vista-family-center/
  # 10)
  - /live/roots-wings/


winners:
  # 1)
  - /learn/center-for-innovation-in-stem-education-cise/
  # 2)
  - /create/east-la-community-corporation-elacc/
  # 3)
  - /play/the-brady-center-to-prevent-gun-violence/
  # 4)
  - /connect/mirys-list/
  # 5)
  - /live/united-way-of-greater-los-angeles/


auth0_js_url: https://cdn.auth0.com/js/auth0/9.5.1/auth0.min.js
# auth0_domain: activation-la2050.auth0.com
auth0_domain: auth0-activation.la2050.org
auth0_client_id: INfJpr4dnNk2EN143utsZYz4Zeq9c7cd

voting_enable_auth0: true

voting_enable_phone: true
voting_enable_email: true
voting_enable_facebook: true

voting_maintance_mode: false
voting_test_mode: false

voting_strict_mode: true

# For cache busting
version: 2.1.8


permalink: pretty

exclude:
  - CNAME
  - README
  - Gemfile
  - Gemfile.lock
  - _node
  - sitemap.txt
  - assets/images/learn/original
  - assets/images/create/original
  - assets/images/play/original
  - assets/images/connect/original
  - assets/images/live/original
  - assets/images/goals/original
  - assets/images/home/original
  - assets/images/vote/original

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: "2019"
    values:
      layout: project
