
title: 2018 My LA2050 Activation Challenge

mailing_list_url: https://goldhirshfoundation.us6.list-manage.com/subscribe?u=81b6d7b4efb839b992bf7ae72&id=93b6887d2a
submission_url: https://activationla2050.smapply.io/prog/challenge_info/
vote_url: /finalists/
# event_url: /event/

# New challenge announced: 
# February 1
# phase: 1

# Entries being accepted: 
# March 1
# phase: 2

# Entry period ended: 
# March 31
# phase: 3

# Entries shown on the website: 
# April 9 
phase: 4

# 25 finalists announced: 
# May 21
# phase: 5

# Votes being accepted: 
# June 19
# phase: 6

# Voting period ended: 
# June 30 
# phase: 7

# Winners announced: 
# July 9 
# phase: 8

permalink: pretty

version: 1.1.0

exclude:
  - CNAME
  - README
  - node_modules
  - gulpfile.js
  - package.json
  - package-lock.json

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: learn
    values:
      layout: project
      body_class: blueberry
  - scope:
      path: ""
      type: create
    values:
      layout: project
      body_class: banana
  - scope:
      path: ""
      type: play
    values:
      layout: project
      body_class: strawberry
  - scope:
      path: ""
      type: connect
    values:
      layout: project
      body_class: tangerine
  - scope:
      path: ""
      type: live
    values:
      layout: project
      body_class: lime

collections:
  learn:
    output: true
    permalink: /learn/:path/
  create:
    output: true
    permalink: /create/:path/
  play:
    output: true
    permalink: /play/:path/
  connect:
    output: true
    permalink: /connect/:path/
  live:
    output: true
    permalink: /live/:path/
