
title: 2020 My LA2050 Grants Challenge
description: >-
  The My LA2050 Grants Challenge is an open call for ideas to make LA the best place to
  learn, create, play, connect, and live.
image: https://challenge.la2050.org/assets/images/city-illustration/square.png

mailing_list_url: https://la2050.us6.list-manage.com/subscribe/post?u=81b6d7b4efb839b992bf7ae72&amp;id=b16f498212
submission_url: https://challengela2050.smapply.io

# Our form:
vote_url: /vote/form/

year: 2020
show_early_entries: true

image_host: 'https://challenge-static.la2050.org'


NEW_CHALLENGE_ANNOUNCED: 1
ENTRIES_BEING_ACCEPTED: 2
ENTRY_PERIOD_ENDED: 3
ENTRIES_SHOWN_ON_THE_WEBSITE: 4
VOTES_BEING_ACCEPTED: 5
VOTING_PERIOD_ENDED: 6
FINALISTS_ANNOUNCED: 7
WINNERS_ANNOUNCED: 8


# New challenge announced: 
# January 27
# phase: 1

# Entries being accepted: 
# February 3
phase: 2

# Early bird deadline:
# March 1 ?
# phase: ?

# Entry period ended: 
# March 27
# phase: 3

# Entries shown on the website: 
# April 6
# phase: 4

# Finalists announced: 
# May 18
# phase: 5

# Votes being accepted: 
# June 1
# phase: 6

# Voting period ended: 
# June 8
# phase: 7

# Winners announced: 
# June 15
# phase: 8


finalists:

  # Learn

  # 1)
  - /2020/learn/9-dots/

  # 2)
  - /2020/learn/center-for-innovation-in-stem-education-cise/

  # 3)
  - /2020/learn/freedom-and-fashion/

  # 4)
  - /2020/learn/fulfillment-fund/

  # 5)
  - /2020/learn/gladeo/


  # Create

  # 1)
  - /2020/create/bob-baker-marionette-theater/

  # 2)
  - /2020/create/defy-ventures-inc/

  # 3)
  - /2020/create/everybody-world/

  # 4)
  - /2020/create/homeboy-industries/

  # 5)
  - /2020/create/justice-for-my-sister-collective/


  # Play

  # 1)
  - /2020/play/american-heart-association/

  # 2)
  - /2020/play/city-of-los-angeles-department-of-recreation-and-parks/

  # 3)
  - /2020/play/harlem-lacrosse/

  # 4)
  - /2020/play/los-angeles-audubon-society/

  # 5)
  - /2020/play/los-angeles-dodgers-foundation/


  # Connect

  # 1)
  - /2020/connect/breathe-california-of-los-angeles-county/

  # 2)
  - /2020/connect/c-it-productions-llc/

  # 3)
  - /2020/connect/casa-of-los-angeles/

  # 4)
  - /2020/connect/human-rights-foundation/

  # 5)
  - /2020/connect/investing-in-place/


  # Live

  # 1)
  - /2020/live/cardborigami-inc/

  # 2)
  - /2020/live/green-girl-farms/

  # 3)
  - /2020/live/international-association-for-human-values/

  # 4)
  - /2020/live/la-plaza-de-cultura-y-artes/

  # 5)
  - /2020/live/move-la/


winners:

  # Learn:

  # 1) 9 Dots
  - /2020/learn/9-dots/

  # 2) Rise, Inc.
  - /2020/learn/rise-inc/


  # Create: 

  # 1) Defy Ventures
  - /2020/create/defy-ventures-inc/

  # 2) Venice Community Housing
  - /2020/create/venice-community-housing/


  # Play:

  # 1) Harlem Lacrosse
  - /2020/play/harlem-lacrosse/

  # 2) Natural History Museum
  - /2020/play/natural-history-museum-of-los-angeles-county/


  # Connect:

  # 1) CASA
  - /2020/connect/casa-of-los-angeles/

  # 2) Rock the Vote
  - /2020/connect/rock-the-vote/


  # Live:

  # 1) The Youth Movement Against Alzheimer's
  - /2020/live/the-youth-movement-against-alzheimers/

  # 2) La Plaza de Cultura Y Artes
  - /2020/live/la-plaza-de-cultura-y-artes/


auth0_js_url: https://cdn.auth0.com/js/auth0/9.5.1/auth0.min.js
# auth0_domain: activation-la2050.auth0.com
auth0_domain: auth0-activation.la2050.org
auth0_client_id: INfJpr4dnNk2EN143utsZYz4Zeq9c7cd

voting_enable_auth0: true

voting_enable_phone: true
voting_enable_email: true
voting_enable_facebook: true

voting_maintance_mode: false
voting_test_mode: false

voting_strict_mode: false

# For cache busting
version: 2.2.9


permalink: pretty

exclude:
  - CNAME
  - README
  - Gemfile
  - Gemfile.lock
  - _node
  - sitemap.txt
  - test-finalists.txt
  - assets/images/2019/learn/original
  - assets/images/2019/create/original
  - assets/images/2019/play/original
  - assets/images/2019/connect/original
  - assets/images/2019/live/original
  - assets/images/2019/learn/original
  - assets/images/2019/create/original
  - assets/images/2019/play/original
  - assets/images/2019/connect/original
  - assets/images/2019/live/original
  - assets/images/2020/learn/original
  - assets/images/2020/create/original
  - assets/images/2020/play/original
  - assets/images/2020/connect/original
  - assets/images/2020/live/original
  - assets/images/2020/learn/original
  - assets/images/2020/create/original
  - assets/images/2020/play/original
  - assets/images/2020/connect/original
  - assets/images/2020/live/original
  - assets/images/goals/original
  - assets/images/home/original
  - assets/images/vote/original

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: "2019"
    values:
      layout: project
  - scope:
      path: ""
      type: "2020"
    values:
      layout: project

collections:
  '2019':
    output: true
    permalink: /2020/:path/
  '2020':
    output: true
    permalink: /2020/:path/
